### ISSUE TITLE
[BUG] ETS unable to fix windows

### ISSUE THREAD

**Issue by BlackoutOnstrike** [Manufacturing-Department/issue-tracker#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live Reserved Server

### Game Version

889

### Expected Behavior

Expected behavior is that ETS is able to repair the window but in this case ETS isn't able to repair the window.

### Steps To Reproduce

1. Go on ETS team
2. Head to omicron viewing area
3. Shoot the window until it breaks
4. Try to repair it with the wrench

### Anything else?

https://medal.tv/games/roblox/clips/aCwymTog1aczp/d1337MSRPcM9?invite=cr-MSxSU3QsMTkzMDg2NDQs

**Comment by spenserm10** [comment]
Was that a feature? I never knew E&TS were able to repair windows like ever.

**Comment by SamMP4** [comment]
Ok to end this discussion, ETS are not supposed to be able to repair the window. I am a former ETS member and can confirm that the wrench no longer does anything ON PURPOSE. Features may be added in the future but currently it doesn't repair anything.
