### ISSUE TITLE
[BUG] When joining, you can see yourself on the spawn for a second or two.

### ISSUE THREAD

**Issue by Axiewu** [Manufacturing-Department/issue-tracker#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

888 

### Expected Behavior

Currently, you can see yourself on the spawn and flat map when spawning for a second or two. I suppose the screen should appear for more time so players won't see themselves on the spawn.

### Steps To Reproduce

1. Join the game
2. Look before the server menu appears

### Anything else?

![image](https://user-images.githubusercontent.com/99291801/153570001-2c785388-9ad9-4bbb-aac3-75d9b2e14d2d.png)

**Comment by Paul19988** [comment]
Intended behaviour.
