### ISSUE TITLE
[BUG] Some people (SD in this case) keep loosing their keycard. 

### ISSUE THREAD

**Issue by Axiewu** [Manufacturing-Department/issue-tracker#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

888 "Imaginative Elecwing"

### Expected Behavior

What is happening? Their keycard keeps dropping down, they must go print new one instead. 
Expected behaviour? Their keycard stays with them and doesn't drop down.

### Steps To Reproduce

Unsure

### Anything else?

None, didn't get much information aside from that. They also tried rejoining and double-m ing.

**Comment by Paul19988** [comment]
Cannot reproduce.
