### ISSUE TITLE
[BUG] QA Team unable to open catwalk door

### ISSUE THREAD

**Issue by akiilux** [Manufacturing-Department/issue-tracker#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

888

### Expected Behavior

Door should open upon pressing E.

### Steps To Reproduce

1. Enter CDC.
2. Go up the ladder.
3. Walk onto the short catwalk.
4. Try open door at end.
5. Door does not open.

### Anything else?

![unknown](https://user-images.githubusercontent.com/99290139/153640146-942dcd42-d14b-46d1-923b-508d3e9511d3.png)

Reported by Axiewu.

**Comment by Paul19988** [comment]
Staged.
