### ISSUE TITLE
[BUG] Bins in Omicron laundry room are broken

### ISSUE THREAD

**Issue by akiilux** [Manufacturing-Department/issue-tracker#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

888

### Expected Behavior

Prompt to use bin should appear.

### Steps To Reproduce

1. Enter Omicron.
2. Head down to residential level.
3. Enter laundry room.
4. Approach bin.
5. No prompt to use appears.

### Anything else?

![image](https://user-images.githubusercontent.com/99290139/153641520-cdf5f50e-a0ba-4587-9735-4f42bd64b28e.png)

**Comment by Paul19988** [comment]
Staged.
