### ISSUE TITLE
[BUG] Extremely dark in upper elevator area (Technical Wing)

### ISSUE THREAD

**Issue by akiilux** [Manufacturing-Department/issue-tracker#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

888

### Building Bug Information

![image](https://user-images.githubusercontent.com/99290139/153643904-37fa779c-0e23-49f1-987e-884980bc34fb.png)

Really dark in the upper Technical Wing elevator area.

**Comment by Paul19988** [comment]
Staged.
