### ISSUE TITLE
[BUG] Omicron transfer gate entrance & exit Z-Fighting

### ISSUE THREAD

**Issue by v7-c** [Manufacturing-Department/issue-tracker#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

891

### Building Bug Information

Z-Fighting occurs at entrance and exit to both omicron CDC transfer gates, most likely due to floor and door edge bottom. Non-urgent.

### Anything else?

https://gyazo.com/b3e6807c938f09ca33bda0cf491d4325

**Comment by Paul19988** [comment]
Staged.
