### ISSUE TITLE
[BUG] Able to see outside map by being on top of the CCTV near Phi entrance.

### ISSUE THREAD

**Issue by camkitchen** [Manufacturing-Department/issue-tracker#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

910

### Expected Behavior

I'd expect to not be able to jump onto the CCTV TV, and not be able to see the outside of the map if I did. I would also expect there to be not possible way to get on top of the CCTV.

### Steps To Reproduce

1. Go on top of the garbage cans.
2. Go into first person so you can squeeze you body on top of the CCTV
3. Go back into third person, being able to freely look outside of the map, wherever you want.

### Anything else?

This is the location of the bug:
![RobloxScreenShot20220211_190124461](https://user-images.githubusercontent.com/99302549/153687078-57baf996-c9a0-42bc-ba27-e4cfd0983e4f.png)
This is what happens when you do the steps:
![RobloxScreenShot20220211_190138496](https://user-images.githubusercontent.com/99302549/153687111-b7d85411-c497-4133-bc22-20dcd2b50d4b.png)

**Comment by Paul19988** [comment]
Staged.
