### ISSUE TITLE
[BUG] Radiation can be heard in DMR Control Room

### ISSUE THREAD

**Issue by boopxyz** [Manufacturing-Department/issue-tracker#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

878

### Expected Behavior

Radiation should not be heard in the DMR control room

### Steps To Reproduce

1. Go to DMR Control Room without a hazmat suit on
2. Get close to the glass railing and you will hear radiation

### Anything else?

ET&S reported it to me and wanted it fixed due to a confusion with a radiation leak.

**Comment by dr-k4rma** [comment]
From what I know, this is an intended feature, not a bug.
Radiation even in real life cannot be blocked 100% of the time.

**Comment by boopxyz** [comment]
> From what I know, this is an intended feature, not a bug. Radiation even in real life cannot be blocked 100% of the time.

Gotcha, only reported it because ETS requested I do so.
