### ISSUE TITLE
[BUG] You can see the outside of the map on the vending machines in SA.

### ISSUE THREAD

**Issue by curbalas** [Manufacturing-Department/issue-tracker#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live Private Server

### Game Version

918

### Expected Behavior

When you get on the vending machines that I showed in the clip, you get stuck and see outside of the map.

### Steps To Reproduce

1- Go to the room near DMR observation that has vending machines
2- Get on the vending machines
3- See the outside of the map

### Anything else?

https://medal.tv/games/roblox/clips/b1CRhgaBGLT9C/d1337g1cZdpZ?invite=cr-MSxVR1UsMzExNjYxOTUs

![image](https://user-images.githubusercontent.com/99288227/153881602-a7c132ff-83a8-455e-a4e1-ee0c0580d796.png)
![image](https://user-images.githubusercontent.com/99288227/153881615-93628a5d-f20e-4f5b-8b65-10c38d37a7c8.png)

**Comment by Paul19988** [comment]
Staged.
