### ISSUE TITLE
[BUG] Several broken Garbage Bins in-game are broken

### ISSUE THREAD

**Issue by spenserm10** [Manufacturing-Department/issue-tracker#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

Version 918 *Self-confident Spidow*

### Expected Behavior

I would expect all of the garbage bins to pop up with the e prompt to remove my lunch tray, but over half of them on-site don't, and it's more or less a "prop". It makes me mad when I walk halfway across somewhere to get to one to discard my leftover food, but they don't even work. (To make it obvious, the locations are **below** the pictures.) Pictures with locations below:
![working_BinBug](https://user-images.githubusercontent.com/30034482/153995659-95eabfbf-a827-4cd2-990b-0033509b5c66.png)
**This is what the WORKING prompt should look like, how it should normally act.**

These are how they act now. v
![MTFSpawn_BinsBug](https://user-images.githubusercontent.com/30034482/153993514-f1d5d541-a644-4b3d-91d3-0b26e9090d2d.png)
**Second floor right outside of Gymnasium in MTF Spawn.**
(Was reported on Nolt by myself) [More broken garbage bins#3978](https://nolt.scpf.io/3978)

![MTFSpawn_BinsBug2](https://user-images.githubusercontent.com/30034482/153993565-fc6c7554-d5ee-46ec-b79f-efd427c7f46b.png)
**Second floor at the end of the catwalk near staircase in MTF Spawn.**
(Was reported on Nolt by myself) [More broken garbage bins#3978](https://nolt.scpf.io/3978)

![CR_BinBug2](https://user-images.githubusercontent.com/30034482/153993515-db76145e-c381-4ebe-973e-8ae07ff7f445.png)
**At the entrance of Research Wing.**

![CR_BinBug](https://user-images.githubusercontent.com/30034482/153993516-827bfb71-f9ed-4ea9-8429-2b3fa6cd408d.png)
**Right inside of Clean-Rooms all the way down the hallway.**

![Phi_BinBug6](https://user-images.githubusercontent.com/30034482/153993517-010f2817-d8b7-42b2-87fd-f21978cbcac2.png)
**Inside of the Medical Department Lobby area. (Behind the checkin board).**

![Phi_BinBug5](https://user-images.githubusercontent.com/30034482/153993519-4c558c83-eeef-4c86-877d-94bb596190c0.png)
**Inside the Medical Department Lobby area. (Next to the vending machines).**

![Phi_BinBug4](https://user-images.githubusercontent.com/30034482/153993523-e3d2e068-c8b8-498a-8d9c-df7835fb1f9d.png)
**Inside the breach shelter near the beds.**

![Phi_BinBug3](https://user-images.githubusercontent.com/30034482/153993524-57d09a0c-ed65-44cf-ba40-e724711cd9bd.png)
**Right next to the Phi Gymnasium and FP Spawn.**

![Phi_BinBug2](https://user-images.githubusercontent.com/30034482/153993527-78adae20-6ce7-4c14-b73a-e0863684f77e.png)
**In the Phi Cafeteria right under the status board.**
(Was reported on Nolt) [Garbage Cans in Phi Cafeteria don't work#3929](https://nolt.scpf.io/3929)

![Phi_BinBug](https://user-images.githubusercontent.com/30034482/153993528-64214cd9-c6f3-4bb4-aa44-a5d32a3e692e.png)
**The Phi Monorail at Platform 1.**

![SA_BinBug7](https://user-images.githubusercontent.com/30034482/153993530-4959a1cd-27b9-4da1-bd37-1c1232ae0c5c.png)
**Site Alpha Monorail station. On the most outer part of the monorail platform.**

![SA_BinBug6](https://user-images.githubusercontent.com/30034482/153993532-ad0e0f93-6f4d-454c-944e-d503c34cc82c.png)
**Site Alpha Monorail past the "ticket collectors" but right before the blast door.**

![SA_BinBug5](https://user-images.githubusercontent.com/30034482/153993533-120ae323-db47-46e9-b52e-ade428b3b305.png)
**Site Alpha DMR Observation Room.**

![SA_BinBug4](https://user-images.githubusercontent.com/30034482/153993534-2a6006e8-ceb0-492b-b6a4-67be5d169852.png)
**Site Alpha middle area right after the elevators leading from Site Alpha monorail station to the Site Alpha Observation. In this image, the observation room is to the right, and the rest of Site Alpha is to the left.**

![SA_BinBug3](https://user-images.githubusercontent.com/30034482/153993535-f38c1093-8682-4a56-b5aa-c4eee408b740.png)
**Site Alpha, main entrance right after the large blast door.**

![SA_BinBug2](https://user-images.githubusercontent.com/30034482/153993536-aedbf61f-8264-4a81-b791-ed9871ffa016.png)
**Site Alpha, main entrance before the large blast door. Very first garbage bins when you walk in the place.**

![SA_BinBug](https://user-images.githubusercontent.com/30034482/153993537-8432a263-c5ff-4c3c-a540-bad5ecbd495c.png)
**Site Alpha, main entrance past the lower wall right before blast door.**

![CDCLowerLaundry_BinBug](https://user-images.githubusercontent.com/30034482/153993543-9c44f575-28f9-44b5-9b9c-ba1c77d6548c.png)
**The monorail level Laundry Room.** (Has already been reported but to put it in a centralized location I've included it here.) [[BUG] Bins in Omicron laundry room are broken #46](https://github.com/Manufacturing-Department/issue-tracker/issues/46)

![CDC_BinBug2](https://user-images.githubusercontent.com/30034482/153993552-c241bdd6-461c-40ad-982a-db14a077eff1.png)
**In the "Visitation" Rooms in the CDC right next to lower Observation.**

![CDCBasketball_BinBug](https://user-images.githubusercontent.com/30034482/153993560-5c6caacf-3605-4f61-9823-f08c19c8173c.png)
**In the CDC on the far end of the Basket Ball court (right before the cells)**

If you have any questions about locations, just ask.

### Steps To Reproduce

1. Pick up a tray of food from anywhere
2. Try to throw it away in any of the listed garbage bins
3. Realize they don't work and feel disappointed

(Will happen every time, not a caused bug but is by default broken).

### Anything else?

Nothing else to add.

**Comment by Paul19988** [comment]
Staged.
