### ISSUE TITLE
[BUG] You can't put items down on the EUC, after spawning one (EUC) while holding an item.

### ISSUE THREAD

**Issue by Axiewu** [Manufacturing-Department/issue-tracker#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

918 - "Self-Confident Spidow"

### Expected Behavior

What's happening? While holding an item / box, once you spawn an EUC holding it, you cannot place it (the box) on the EUC
Expected Behavior? You can put it down on the EUC after spawning one while holding it.

### Steps To Reproduce

1. Join any server
2. Pick any box up (item prefferably) 
3. Spawn an EUC
4. Try to put it down.

### Anything else?

![image](https://user-images.githubusercontent.com/99291801/154036670-6fe0b6d1-ed82-4437-98ac-f2602f8f1940.png)

**Comment by Paul19988** [comment]
NAB (Not a bug) - This isn't a bug but intended behaviour, they must spawn the cart before picking up the box.
