### ISSUE TITLE
[BUG] Floor anomaly in hallway leading away from Omicron cafeteria to the Motorpool

### ISSUE THREAD

**Issue by akiilux** [Manufacturing-Department/issue-tracker#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

918

### Building Bug Information

![image](https://user-images.githubusercontent.com/99290139/154142046-ccf2d3d9-e286-44ea-9990-9df11433e740.png)

Very minor detail in the flooring of the hallway.

### Anything else?

N/A

**Comment by Paul19988** [comment]
Staged.
