### ISSUE TITLE
[BUG] Bins broken in the big open pit near the LD depot

### ISSUE THREAD

**Issue by akiilux** [Manufacturing-Department/issue-tracker#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

918

### Expected Behavior

Prompt to use bin should appear.

### Steps To Reproduce

1. Approach bin.
2. No prompt to use bin appears.

### Anything else?

![image](https://user-images.githubusercontent.com/99290139/154355087-cbd9f63d-75b3-4168-ac70-876d61af3098.png)

**Comment by Paul19988** [comment]
Staged.
