### ISSUE TITLE
[BUG] Crimson-9 (Maybe all of MTF) are unable to open the downstairs Omicron Cafeteria Door.

### ISSUE THREAD

**Issue by spenserm10** [Manufacturing-Department/issue-tracker#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

Version **919** *Fearless Glacicon*

### Expected Behavior

I would expect to be able to open this door instead of having to walk around.
It is located at the basement level at Omicron, so if you come from the Omicron Monorail through the access shaft area to the Omicron Cafeteria, at the top of the stairs (right outside of it) you cannot open the door. Directly across from the elevator.
![PathosOmicronCafeBug](https://user-images.githubusercontent.com/30034482/154790070-2f461f33-4038-48cf-8c1d-089292c60f53.png)
![PathosOmicronCafeBug2](https://user-images.githubusercontent.com/30034482/154790073-489d88b9-981e-4b93-996b-daf7de9a9597.png)

### Steps To Reproduce

1. Try to open door as Crimson-9
2. Realize it won't open.

### Anything else?

Nothing else to add.

**Comment by NegativeValk** [comment]
t

**Comment by Paul19988** [comment]
It is to my understanding that the live game still does not contain the changed permissions on that door.
