### ISSUE TITLE
[BUG] Omicron Activities Center Bench Facing Backwards

### ISSUE THREAD

**Issue by Enkoes** [Manufacturing-Department/issue-tracker#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Location

Live

### Game Version

Version 933

### Expected Behavior

In the Activities Center on the third floor in Omicron, there is a particular bench that happens to be facing backwards. This means that when you try and sit anywhere on that bench, your character will be facing backwards rather than the expected direction that they should be facing.

### Steps To Reproduce

1. Head to the third floor at Site Omicron and head into the Activities Center.
2. Near the weights and treadmills, locate the bench FARTHEST from the two vending machines in the corner.
3. Try and sit on any of the two spots on the bench, and your character will be sitting backwards.

### Anything else?

https://medal.tv/games/roblox/clips/c7tU7SRz3lHfZ/d1337T0mmdHO?invite=cr-MSxWSWgsMTM3OTg1NTEs

**Comment by NegativeValk** [comment]
Can reproduce 
Negative#9033

**Comment by Paul19988** [comment]
Staged.
